version: '3.9'

networks:
  jenkins: # This line should be indented by 2 spaces relative to 'networks:'

volumes:
  jenkins-data: # This line should be indented by 2 spaces relative to 'volumes:'
  jenkins-docker-certs: # This line should be indented by 2 spaces relative to 'volumes:'

services:
  dind: # This line should be indented by 2 spaces relative to 'services:'
    image: docker:dind # This line and subsequent lines for 'dind' should be indented by 4 spaces
    privileged: true
    restart: unless-stopped
    networks:
      jenkins:
        aliases:
          - docker
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"

  jenkins: # This line should be indented by 2 spaces relative to 'services:'
    image: jenkins/jenkins:lts # This line and subsequent lines for 'jenkins' should be indented by 4 spaces
    container_name: jenkins
    restart: on-failure
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
    ports:
      - "8080:8080"
      - "50000:50000"